# config file for automatic testing at travis-ci.org
language: python

python:
    - "2.7"

install:
    # install dependencies
    - pip install pytest
    - pip install --editable .

script:
    # command to run tests and collect test coverage
    - py.test -v tests/

notifications:
    email: false
