# config file for automatic testing at travis-ci.org
language: python

python:
    - "3.6"

services:
    - mongodb

install:
    # update periodically - saves downloading if version is the same
    - if [[ "${TRAVIS_PYTHON_VERSION}" == "2.7" ]]; then
          wget https://repo.continuum.io/miniconda/Miniconda-latest-Linux-x86_64.sh -O miniconda.sh;
      else
          wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
      fi
    - bash miniconda.sh -b -p "${HOME}/miniconda"
    - export PATH="${HOME}/miniconda/bin:$PATH"
    - hash -r
    - conda config --set always_yes yes --set changeps1 no
    - conda update -q conda
    # useful for debugging any issues with conda
    - conda info -a

    # create a new conda env
    - conda create -q -n test-environment python=$TRAVIS_PYTHON_VERSION pytest coverage numpy cython
    - source activate test-environment
    # install dependencies
    - pip install pytest
    - pip install --editable .

script:
    # command to run tests and collect test coverage
    - pip list
    - py.test -v tests/

notifications:
    email: false
