site_name: loqusdb documentation
site_url: https://clinical-genomics.github.io/loqusdb
repo_url: https://github.com/Clinical-Genomics/loqusdb
site_author: Måns Magnusson and Jesper Eisfeldt
docs_dir: docs

theme:
  name: 'material'
  # logo: 'cloud_circle'
  palette:
    primary: 'blue grey'
    accent: 'cyan'

nav:
  - Home: 'README.md'

  - Installation: 'install.md'

  - User Guide:
    - User Guide README: 'user-guide/README.md'
    - Loading: 'user-guide/loading.md'
    - Deleting: 'user-guide/deleting.md'
    - Exporting: 'user-guide/exporting.md'
    - Annotating: 'user-guide/annotating.md'
    - Profiling: 'user-guide/profiling.md'

  - Admin Guide:
    - Admin Guide README: 'admin-guide/README.md'
    - Dump database: 'admin-guide/dump.md'
    - Restore database: 'admin-guide/restore.md'

