name: Publish to PyPI

on:
 release:
  types:
   - created


jobs:
 build-n-publish:
  name: Build and publish Python distribution to PyPI
  runs-on: ubuntu-latest
  steps:
   - name: Check out git repository
     uses: actions/checkout@v4

   - name: Set up Python
     uses: actions/setup-python@v5
     with:
      python-version: 3.12

   - name: Install poetry
     uses: snok/install-poetry@v1

   - name: Build and Publish Distribution to PyPI 📦
     env:
       PYPI_USERNAME: __token__
       PYPI_PASSWORD: ${{ secrets.pypi_password }}
       POETRY_REQUESTS_TIMEOUT: 60
     run: |
       poetry publish --no-interaction --build \
         --username $PYPI_USERNAME \
         --password $PYPI_PASSWORD


 deploy-docs:
    name: Deploy Docs to GitHubIO
    runs-on: ubuntu-latest
    steps:
     - name: Checkout repo
       uses: actions/checkout@v4
     - name: Setup environment for docs deployment
       uses: actions/setup-python@v5
       with:
         python-version: 3.x
     - name: Install mkdocs
       run: pip install mkdocs mkdocs-material markdown-include
     - name: Deploy documentation
       run: mkdocs gh-deploy --force
